baseurl = "https://textfile.io"
pluralizeListTitles = false
staticDir = ["static"]
languageCode = "en-us"
title = "Textfile"
theme = "hugo-tufte"
# theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 2

[params]
  dark = "off"
  highlight = true
  copyright = ""
  showPoweredBy = false
  iso8601_format = "2006-01-02T15:04:05Z07:00"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[[menu.nav]]
  name = "Home"
  pre = "<i class='fa fa-home fa-lg'></i> "
  weight = -110
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Posts"
  pre = "<i class='fa fa-book fa-lg'></i> "
  weight = -100
  identifier = "posts"
  url = "/posts"

