baseurl = "https://textfile.io"
staticDir = ["static"]
languageCode = "en-us"
title = "Textfile"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    lineNoStart = 1
    lineNumbersInTable = true
    noClasses = false
    style = "github"
    tabWidth = 2

[params]
  dark = "off"
  highlight = true

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]
